### ISSUE TITLE
[Bug] Random Ban

### ISSUE THREAD

**Issue by TheRobLP** [kangarko/PunishControl#2]
### How to ask questions or report a problem here?
**If you want to get your question answered quickly, please stick to those three rules:**

### 1 - Write your Minecraft version in the title:
git-paper 312 ; Version: 1.15.2

### 2 - Be clear: What is your current situation, the desired situation, and your problem?

Today one of my moderators was randomly banned by the system while simply playing. No one used a command to ban the user, and this was in Bungeecord console:

21:08:37] [Netty Worker IO Thread #29/INFO]: [*Loganh4005] disconnected with: 

You have been banned
Reason: Example
Expiration: 06:43 16/06/2020
[21:08:37] [nioEventLoopGroup-8-2/INFO] [Geyser-BungeeCord]: Loganh4005 has disconnected from remote java server on address [IP] because of 

You have been banned

I should note that Im using a plugin called "GeyserMC" which lets Bedrock players join our Java servers. But I think it shouldn´t matter, since the plugin should not auto-ban, right?

### 3 - Upload your plugin's folder.

Folder link will be sent to a staff member in DMs on request, to protect our players IP-adresses

Thank you.

**Comment by JavaFactoryDev** [comment]
Hi TheRobLP,

Thank you for reporting this issue here.

PunishControl doesn't autoban. This feature doesn't exist.
Whats might be possible is that your moderator had the same IP as a banned user. (You can disable blocking IP's in the console)
But this wouldn't disconnect users. (Maybe there is an exception because of ur allowing bedrock players to join)

As any punishments in PunishControl needs to have a creator, please tell me who the creator of the punishment is. 

P.S.
As it seems the player was banned from the example-ban template. Are you really sure nobody of your stuff team did this?

Regards,
Leonhard from MineAcademy
